# Generated by Django 5.2 on 2025-05-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClickerAPI', '0002_ageuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgeUser',
        ),
    ]
