# Generated by Django 5.2 on 2025-05-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClickerAPI', '0004_clickcount_delete_clickcounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickcount',
            name='user',
        ),
        migrations.AddField(
            model_name='clickcount',
            name='ip',
            field=models.GenericIPAddressField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clickcount',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
