# Generated by Django 5.2 on 2025-06-03 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClickerAPI', '0006_alter_clickcount_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='clickcount',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clicker_user', to='ClickerAPI.stuff'),
            preserve_default=False,
        ),
    ]
