# Generated by Django 5.2 on 2025-06-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClickerAPI', '0007_stuff_clickcount_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickcount',
            old_name='user',
            new_name='stuff_status',
        ),
        migrations.AddField(
            model_name='stuff',
            name='email',
            field=models.EmailField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stuff',
            name='stuff_name',
            field=models.CharField(max_length=40),
        ),
    ]
