# Generated by Django 5.2 on 2025-06-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClickerAPI', '0008_rename_user_clickcount_stuff_status_stuff_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='email',
            field=models.EmailField(default='None', max_length=60),
        ),
    ]
