# Generated by Django 5.2 on 2025-06-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClickerAPI', '0009_alter_stuff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='email',
            field=models.EmailField(blank=True, max_length=60),
        ),
    ]
