# Generated by Django 5.2 on 2025-06-11 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClickerAPI', '0011_alter_clickcount_stuff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickcount',
            name='stuff_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicker_user', to='ClickerAPI.stuff'),
        ),
    ]
