# Generated by Django 5.2 on 2025-06-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClickerAPI', '0012_alter_clickcount_stuff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickcount',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='stuff_name',
            field=models.CharField(default='Игрок', max_length=40),
        ),
    ]
