# Generated by Django 5.2 on 2025-06-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClickerAPI', '0013_alter_clickcount_ip_alter_stuff_stuff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='stuff_name',
            field=models.CharField(max_length=40),
        ),
    ]
